#!/usr/bin/env python

import sys
import os

try:
    import sageui
except ImportError:
    app_home_dir = os.path.abspath(os.path.dirname(sys.argv[0]))
    sys.path.append(os.path.join(app_home_dir, 'src'))
    import sageui


if __name__ == '__main__':
    from sageui.cmdline import launch
    launch()
    


